(load "/Volumes/DATI/GIT/IALAB/micalizio/progetto/MAIN.clp")
(load "/Volumes/DATI/GIT/IALAB/micalizio/progetto/regoleDomande.clp")
(load "/Volumes/DATI/GIT/IALAB/micalizio/progetto/domande.clp")
(load "/Volumes/DATI/GIT/IALAB/micalizio/progetto/appartamenti.clp")
(load "/Volumes/DATI/GIT/IALAB/micalizio/progetto/regole.clp")
(load "/Volumes/DATI/GIT/IALAB/micalizio/progetto/printresult.clp")
(load "/Volumes/DATI/GIT/IALAB/micalizio/progetto/restart.clp")
(reset)
(run)