(load "../Uni/IALAB/micalizio/MAIN.clp")
(load "../Uni/IALAB/micalizio/regoleDomande.clp")
(load "../Uni/IALAB/micalizio/domande.clp")
(load "../Uni/IALAB/micalizio/appartamenti.clp")
(load "../Uni/IALAB/micalizio/regole.clp")
(load "../Uni/IALAB/micalizio/printresult.clp")
(load "../Uni/IALAB/micalizio/restart.clp")
(reset)
(run)