(load "/Volumes/DATI/GIT/IALAB/micalizio/MAIN.clp")
(load "/Volumes/DATI/GIT/IALAB/micalizio/regoleDomande.clp")
(load "/Volumes/DATI/GIT/IALAB/micalizio/domande.clp")
(load "/Volumes/DATI/GIT/IALAB/micalizio/appartamenti.clp")
(load "/Volumes/DATI/GIT/IALAB/micalizio/regole.clp")
(load "/Volumes/DATI/GIT/IALAB/micalizio/printresult.clp")
(reset)
(run)